source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"

# Switch from minima -> Just the Docs
gem "just-the-docs"

group :jekyll_plugins do
  # No plugins for now
end

# Ruby 3 / Jekyll 4 often needs this explicitly
gem "webrick"

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
